version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: anime_postgres
    environment:
      POSTGRES_USER: anime_team
      POSTGRES_PASSWORD: Otaku2025!
      POSTGRES_DB: anime_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - anime_net

  redis:
    image: redis:7
    container_name: anime_redis
    command: redis-server --requirepass RedisAnime2025!
    ports:
      - "6379:6379"
    networks:
      - anime_net

volumes:
  pgdata:

networks:
  anime_net:
    driver: bridge
